sudo: false

language: python

python:
  - "3.8"

before_install:
  - export DISPLAY=:99.0
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements/conda_requirements.txt
  - pip install -r requirements/test_requirements.txt
  - python setup.py install

script: pytest --pep8 --cov=./

notifications:
  email: false

after_success:
  - codecov
