sudo: false

language: python

python:
  - "3.8"

services:
  - xvfb

before_install:
  - export DISPLAY=:99.0
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - pip install "git+https://github.com/pybamm-team/PyBaMM.git@develop"
  - pip install -r requirements/pip_requirements.txt
  - pip install -r requirements/test_requirements.txt
  - pip install -e .
  - conda install -c conda-forge pardiso4py

script: pytest --flake8 --cov=./

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
